<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddToBasketButton</name>
   <tag></tag>
   <elementGuidId>c42bd6f3-d547-4fff-a686-1651993781cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-item/div/dew-card/dew-card-body/dew-row/dew-col[2]/dew-row[1]/dew-col/dew-row[2]/dew-btn/button</value>
   </webElementProperties>
</WebElementEntity>
