<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Catalogs</name>
   <tag></tag>
   <elementGuidId>7f8d214b-25f5-4615-8ad0-7108f69bf1a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-online-store/dew-tabset/div/div[1]/div/div/ul/li[5]/a</value>
   </webElementProperties>
</WebElementEntity>
