<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FavouritesAndPreviouslyUsed</name>
   <tag></tag>
   <elementGuidId>df1f2d24-411e-45a8-ba16-29b277a00a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-online-store/dew-tabset/div/div[1]/div/div/ul/li[2]/a</value>
   </webElementProperties>
</WebElementEntity>
