<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddToBasketPopup</name>
   <tag></tag>
   <elementGuidId>05327ce5-475e-43e5-8a11-1073675573eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-add-to-basket-modal/dew-modal/div/div/div[1]/h5</value>
   </webElementProperties>
</WebElementEntity>
