<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchIcon</name>
   <tag></tag>
   <elementGuidId>3c36648a-0c8a-4b97-b323-8531fd08c427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-search-results/div/dew-row/dew-col[1]/dew-collapse[6]/div[2]/eproc-value-filter/div/dew-icon</value>
   </webElementProperties>
</WebElementEntity>
