<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FavouriteItemNameHyperlink</name>
   <tag></tag>
   <elementGuidId>8127f6b4-a502-4c8c-86d5-2db2367b90d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-favourites-listing/div/dew-tabset/div/div[2]/div/dew-tab[1]/dew-tabset/div/div[2]/div/dew-tab[1]/dew-block/dew-row[1]/dew-col[1]/eproc-product-card/dew-card/dew-row/dew-col[3]/dew-row[2]/span</value>
   </webElementProperties>
</WebElementEntity>
