<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ViewAll</name>
   <tag></tag>
   <elementGuidId>91bfe366-e215-4351-8392-70792d53fe3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-online-store/dew-tabset/div/div[2]/div/dew-tab[2]/dew-section/dew-flex/dew-flex-item[2]/dew-section-header/dew-btn[3]/button</value>
   </webElementProperties>
</WebElementEntity>
