<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CartItemsListing</name>
   <tag></tag>
   <elementGuidId>28f3fb31-9d6d-47e7-babd-d98ef6fc1860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//eproc-cart-items/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-cart-items/div/dew-card</value>
   </webElementProperties>
</WebElementEntity>
