<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CartIcon</name>
   <tag></tag>
   <elementGuidId>3adf5cb4-f9c5-4baf-8a4c-075a9b3b64d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//dew-row/dew-col[2]/dew-btn[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-cart-spotlight/div/div/span</value>
   </webElementProperties>
</WebElementEntity>
