<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddToBasket</name>
   <tag></tag>
   <elementGuidId>c952685b-55c4-4474-84e6-bfd0b1424ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//dew-btn[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-search-results/dew-card/dew-flex/dew-flex-item/dew-btn[2]/button</value>
   </webElementProperties>
</WebElementEntity>
