<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YesButton</name>
   <tag></tag>
   <elementGuidId>127209e3-c531-4a09-b7a1-27868460e7e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-cart-items/dew-modal[2]/div/div/div[3]/dew-modal-footer/dew-btn[1]/button</value>
   </webElementProperties>
</WebElementEntity>
