<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CartIsEmpty</name>
   <tag></tag>
   <elementGuidId>9d6cb215-6382-45b1-bc23-dff863e87053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//eproc-cart-items/div/dew-card/table/tbody/tr/td</value>
   </webElementProperties>
</WebElementEntity>
